# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='information',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
