# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_network_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('internal_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('displayed_name', models.CharField(max_length=256, null=True)),
                ('database_type', models.CharField(max_length=64)),
                ('comments', models.CharField(max_length=4096, null=True)),
                ('num_tables', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='NetworkType',
            fields=[
                ('type_name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('bin_path', models.CharField(max_length=64)),
                ('cmd_lang', models.CharField(max_length=64)),
                ('cmd_lang_def', models.CharField(max_length=256, null=True)),
                ('tcp_ip_enabled', models.CharField(max_length=5)),
                ('constructing_parameters', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('internal_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('table_name', models.CharField(max_length=256)),
                ('created_date', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('fields', models.CharField(max_length=4096)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Database')),
            ],
        ),
        migrations.AlterField(
            model_name='network',
            name='displayed_name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.NetworkType'),
        ),
    ]
